### ISSUE TITLE
¿what is the mix function?

### ISSUE THREAD

**Issue by blacktrue** [mikield/adonis-user-policy#1]
Hi, i have the following error

ReferenceError: mix is not defined

My code is:

`module.exports = mix(User).with(Policy)`

**Comment by mikield** [comment]
@blacktrue Can you check if all dependecies was installed properly? :)

This package depends on https://github.com/mikield/adonis-true-traits whitch is registering a gloabl function `mix`

UPD:
As fahr as I understand for now fast fix should be adding `@mikield/adonis-true-traits` to `providers` array in the configuration.

**Comment by kingleuther** [comment]
@mikield  my friend, Im also having the same error, mix is not defined. Do you already have a concrete fix on this?

**Comment by mikield** [comment]
@kingleuther there are no fix for it.
Installing https://github.com/mikield/adonis-true-traits and adding ```@mikield/adonis-true-traits``` to providers should resolve the issue.

I will add the lib into dependecies and add information into Readme about registering ```@mikield/adonis-true-traits``` into providers.

**Comment by mikield** [comment]
A new version was released.
Please update and try again.

If you get any errors — feel free to create new issue.
