### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by kingleuther** [mikield/adonis-user-policy#2]
I want to know if the creator is still active, thank you

**Comment by mikield** [comment]
@kingleuther yes I am. Do you need something?

**Comment by kingleuther** [comment]
@mikield  i will be using your library, in case I get into any trouble, can I ask for your guidance and/or help?

**Comment by mikield** [comment]
Yes, of course. I will support it and fix any issues as fast as i can.

ср, 6 июн. 2018 г., 11:03 Leuther Mojica <notifications@github.com>:

**Comment by kingleuther** [comment]
@mikield thanks! I will let you know if I encounter an error
