### ISSUE TITLE
unregistered namespace

### ISSUE THREAD

**Issue by kingleuther** [mikield/adonis-user-policy#3]
I used your library, registered the provider that was mentioned in the first issue. 
It gives me an error, unregistered namespace.

**Comment by kingleuther** [comment]
Cannot read property 'startsWith' of undefined

**Comment by kingleuther** [comment]
`const Model = use('Model')
const PolicyTrait = use('@mikield/adonis-user-policy')
class User extends Model {
    static get policy(){
        return 'App/Policies/Post'
      }
}

module.exports = mix(User).with(PolicyTrait)`

**Comment by mikield** [comment]
@kingleuther in your example you are using it wrong.

1) `const PolicyTrait = use('')` should be `const PolicyTrait = use('@mikield/adonis-user-policy')`
2) This code should be moved to the Post class.
```
static get policy(){
return 'App/Policies/Post'
}
``` 


You should define the policy class into the model which policy will used for.

**Comment by mikield** [comment]
I have released a new version.
Please try to update and if you will face with error — feel free to create new issue.
